name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_check:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: analyze flutter project
        run: flutter analyze
      - name: run unit test
        run: flutter test

  build_android:
    name: android build
    needs: [build_check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle